Repository praveenscience/SoC-LeaderBoard-Test, pull requests merged in 2025-07, with the labels that each got.

#2 Made the Points inside Code. But this should be excluded coz of PA.
  ReadMe.md
Labels: SoCTest25

#12 Added Cases.
  ReadMe.md
Labels: SoCTest25, Advanced

#13 Don't add the base label here but add Beginner or something.
  DontAddBaseLabel.txt
Labels: Beginner

#18 Add base labels and two or three level labels.
  AddMultiLabels.txt
Labels: SoCTest25, Beginner, Advanced

#19 Add Advanced Label then Beginner.
  AddAdvancedFirstThenBeginner.txt
Labels: SoCTest25, Beginner, Advanced
